### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icon didn't comply by the [eOS HIG](https://elementary.io/docs/human-interface-guidelines#shadows) regarding the implementation of pictogram. It should be extruded or inset. So, I modified the icon to fix this.

### CODE REVIEW

**Comment by mdh34** [comment]
I like the redesign but the gradient doesn't match the original HN colours - the icons seem slightly bigger as well

**Comment by Fatih20** [comment]
So, you would like to have color more akin to the previous logo? The bigger icon is supposed to increase visibility since the line arrow is too thin to be visibly seen in smaller sizes of the icon.

**Comment by mdh34** [comment]
Ahh ok, in that case the size is a good idea :) otherwise just the colour would be great

**Comment by mdh34** [comment]
Thanks, these icons look amazing!

**Comment by Fatih20** [comment]
You're welcome! Don't forget to credit me in the release notes!

**Pull request merged**
